### ISSUE TITLE
maxBytesPerFile acts like minBytesPerFile

### ISSUE THREAD

**Issue by kev1n80** [nsqio/go-diskqueue#30]
Since writeOne() checks if the file size exceeds the limit after writing the data instead of checking if writing the data will cause the file size to exceed the limit before writing, this causes the maximum file size to be maxBytesPerFile + maxMsgSize + 3.

**Comment by mreiferson** [comment]
Good catch, I suppose we should do this check the other way around and from a quick scan of the code I think everything else should work (particularly after #23)
